// Supabase Database Types
// This file is auto-generated by Supabase CLI or can be manually defined.
// For now, using a placeholder type.

export type Database = {
  public: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
  }
}